// Code generated by Kitex v0.3.2. DO NOT EDIT.
package noteservice

import (
	"github.com/Ligouhai-bigone/easy_douyin/cmd/api/kitex_gen/commentdemo"
	"github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler commentdemo.NoteService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
