// Code generated by Kitex v0.3.2. DO NOT EDIT.

package noteservice

import (
	"context"
	"github.com/Ligouhai-bigone/easy_douyin/cmd/api/kitex_gen/commentdemo"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SendComment(ctx context.Context, req *commentdemo.SendCommentRequest, callOptions ...callopt.Option) (r *commentdemo.SendCommentResponse, err error)
	GetAllComments(ctx context.Context, req *commentdemo.GetAllCommentsRequest, callOptions ...callopt.Option) (r *commentdemo.GetAllCommentsResponse, err error)
	DeleteComment(ctx context.Context, req *commentdemo.DeleteCommentRequset, callOptions ...callopt.Option) (r *commentdemo.DeleteCommentResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kNoteServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kNoteServiceClient struct {
	*kClient
}

func (p *kNoteServiceClient) SendComment(ctx context.Context, req *commentdemo.SendCommentRequest, callOptions ...callopt.Option) (r *commentdemo.SendCommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendComment(ctx, req)
}

func (p *kNoteServiceClient) GetAllComments(ctx context.Context, req *commentdemo.GetAllCommentsRequest, callOptions ...callopt.Option) (r *commentdemo.GetAllCommentsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAllComments(ctx, req)
}

func (p *kNoteServiceClient) DeleteComment(ctx context.Context, req *commentdemo.DeleteCommentRequset, callOptions ...callopt.Option) (r *commentdemo.DeleteCommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteComment(ctx, req)
}
