// Code generated by Kitex v0.3.2. DO NOT EDIT.

package userservice

import (
	"context"
	"github.com/Ligouhai-bigone/easy_douyin/kitex_gen/userdemo"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, Req *userdemo.RegisterRequest, callOptions ...callopt.Option) (r *userdemo.RegisterResponse, err error)
	GetUser(ctx context.Context, Req *userdemo.GetUserRequest, callOptions ...callopt.Option) (r *userdemo.GetUserResponse, err error)
	CheckUser(ctx context.Context, Req *userdemo.CheckUserRequest, callOptions ...callopt.Option) (r *userdemo.CheckUserResponse, err error)
	FollowUser(ctx context.Context, Req *userdemo.FollowUserRequset, callOptions ...callopt.Option) (r *userdemo.FollowUserResponse, err error)
	UnFollowUser(ctx context.Context, Req *userdemo.UnFollowUserRequset, callOptions ...callopt.Option) (r *userdemo.UnFollowUserResponse, err error)
	GetFollowList(ctx context.Context, Req *userdemo.GetFollowListRequest, callOptions ...callopt.Option) (r *userdemo.GetFollowListResponse, err error)
	GetFollowerList(ctx context.Context, Req *userdemo.GetFollowerListRequest, callOptions ...callopt.Option) (r *userdemo.GetFollowerListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) Register(ctx context.Context, Req *userdemo.RegisterRequest, callOptions ...callopt.Option) (r *userdemo.RegisterResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, Req)
}

func (p *kUserServiceClient) GetUser(ctx context.Context, Req *userdemo.GetUserRequest, callOptions ...callopt.Option) (r *userdemo.GetUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUser(ctx, Req)
}

func (p *kUserServiceClient) CheckUser(ctx context.Context, Req *userdemo.CheckUserRequest, callOptions ...callopt.Option) (r *userdemo.CheckUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckUser(ctx, Req)
}

func (p *kUserServiceClient) FollowUser(ctx context.Context, Req *userdemo.FollowUserRequset, callOptions ...callopt.Option) (r *userdemo.FollowUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowUser(ctx, Req)
}

func (p *kUserServiceClient) UnFollowUser(ctx context.Context, Req *userdemo.UnFollowUserRequset, callOptions ...callopt.Option) (r *userdemo.UnFollowUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UnFollowUser(ctx, Req)
}

func (p *kUserServiceClient) GetFollowList(ctx context.Context, Req *userdemo.GetFollowListRequest, callOptions ...callopt.Option) (r *userdemo.GetFollowListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFollowList(ctx, Req)
}

func (p *kUserServiceClient) GetFollowerList(ctx context.Context, Req *userdemo.GetFollowerListRequest, callOptions ...callopt.Option) (r *userdemo.GetFollowerListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFollowerList(ctx, Req)
}
